# Desafio de classificação da flor de Íris
---
Este desafio consiste no desenvolvimento de um classificador para a flor de Íris.

Primeiramente vamos instalar as bibliotecas necessárias. Neste caso, precisaremos do scipy, numpy, sklearn e matplotlib caso haja necessidade de análise gráfica. Não usaremos o matplotlib, mas é sempre importante tê-lo em mãos.

In [2]:
pip install scipy numpy sklearn matplotlib

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'c:\users\lucas\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.


---
Após a instalação, vamos importar as bibliotecas e pacotes necessários. Utilizaremos os seguintes pacotes:

1. sklearn.datasets import load iris *para utilizar o data set das flores de íris*
2. sklearn.model_selection import train_test_split *para utilizar o sampler para o dataset*
3. sklearn.neighbors import KNeighborsClassifier *para utilizar o método de aprendizagem KNN*
4. numpy

In [25]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression
import numpy as np

Após a importação, precisaremos fazer o load do dataset das iris

In [4]:
iris_dataset = load_iris()
iris_dataset

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

Percebemos que nosso dataset é organizado em dados na posição de largura de sépala, comprimento de sépala, largura de pétala e comprimento de pétala. Esses dados são encontrados na posição de **data**, e os nomes de cada característica podem ser encontrados na posição de **feature_names**.
Além disso, temos três tipos de flores caracterizadas pelos tamanhos: *Setosa*, *Versicolor* e *Virginica*. Esses nomes são encontrados no **target_names**.

---
Podemos observar cada uma das coisas citadas de maneira separada.


In [5]:
print(f'Nome das flores: {iris_dataset["target_names"]}')
print(f'Características observadas: {iris_dataset["feature_names"]}')
print(f'Tipo de dados coletados {type(iris_dataset["data"])}')
print(f'Dados {iris_dataset["data"]}')

Nome das flores: ['setosa' 'versicolor' 'virginica']
Características observadas: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
Tipo de dados coletados <class 'numpy.ndarray'>
Dados [[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4

Vamos checar o formato dos dados, quantas linhas e colunas temos, o tipo, formato e os valores da coluna target

In [6]:
print(f'shape of data: {iris_dataset["data"].shape}')

shape of data: (150, 4)


In [7]:
print(f"Tipo dos targets {type(iris_dataset['target'])}")
print(f"Formato do target: {iris_dataset['target'].shape}")
print(f"Target: \n {iris_dataset['target']}")

Tipo dos targets <class 'numpy.ndarray'>
Formato do target: (150,)
Target: 
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


Aqui dividimos o dataset em treino e teste, o x é a entrada, o y é o resultado a partir da entrada

In [8]:
x_train, x_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state = 0)

Aqui repetimos o processo de ver o formato dos arrays

In [9]:
x_train.shape

(112, 4)

In [10]:
y_train.shape

(112,)

In [11]:
x_test.shape

(38, 4)

In [12]:
y_test.shape

(38,)

Agora criamos nosso classificador. O classificador que utilizamos nesse caso é o KNeighbors. guardamos nosso classificador no objeto knn.

In [13]:
knn = KNeighborsClassifier(n_neighbors = 1)

Aqui treinamos nosso classificador com o x_train e y_train

In [14]:
knn.fit(x_train, y_train)

KNeighborsClassifier(n_neighbors=1)

Aqui fazemos um array com algumas características, características essas que podemos ver nos dados de nosso dataset na parte dos dados, ou **data**

In [15]:
x_new = np.array([[5.9, 3, 5, 0.2]])

Nossa predição é guardada na variável prediction. Para realizar a predição, ou classificar nossa nova entrada, utilizamos o método predict do nosso classificador, passando como parâmetro os nossos novos dados que não são classificados

In [16]:
prediction = knn.predict(x_new)

Nosso prediction classificou os dados informados como uma posição em nosso target_names, abaixo checamos qual foi o resultado

In [17]:
iris_dataset['target_names'][prediction]

array(['versicolor'], dtype='<U10')

Podemos fazer a mesma coisa agora com nosso dataset para testes

In [18]:
y_pred = knn.predict(x_test)

In [19]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

In [24]:
iris_dataset['target_names'][y_pred[:]]

array(['virginica', 'versicolor', 'setosa', 'virginica', 'setosa',
       'virginica', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'virginica', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'setosa', 'versicolor', 'versicolor', 'setosa',
       'setosa', 'virginica', 'versicolor', 'setosa', 'setosa',
       'virginica', 'setosa', 'setosa', 'versicolor', 'versicolor',
       'setosa', 'virginica', 'versicolor', 'setosa', 'virginica',
       'virginica', 'versicolor', 'setosa', 'virginica'], dtype='<U10')

Abaixo checamos o score, ou taxa de acerto de nosso modelo com o Knn

In [20]:
np.mean(y_pred == y_test)

0.9736842105263158

In [22]:
knn.score(x_test, y_test)

0.9736842105263158